#ifndef H_GAME_OBJECT_ATTRIBUTES
#define H_GAME_OBJECT_ATTRIBUTES

namespace ZH::Objects {

enum class AnimationFrameMode {
    RANDOM
  , START_FRAME_FIRST
  , START_FRAME_LAST
  , ADJUST_HEIGHT_BY_CONSTRUCTION_PERCENT
  , PRISTINE_BONE_POS_IN_FINAL_FRAME
  , MAINTAIN_FRAME_ACROSS_STATES
  , RESTART_ANIM_WHEN_COMPLETE
  , MAINTAIN_FRAME_ACROSS_STATES2
  , MAINTAIN_FRAME_ACROSS_STATES3
  , MAINTAIN_FRAME_ACROSS_STATES4
};

enum class AnimationMode {
    LOOP
  , ONCE
  , BACK_AND_FORTH
  , LOOP_BACKWARDS
  , ONCE_BACKWARDS
};

enum class Attribute {
    NONE = 0
  , OBSTACLE
  , SELECTABLE
  , IMMOBILE
  , CAN_ATTACK
  , STICK_TO_TERRAIN_SLOPE
  , CAN_CAST_REFLECTIONS
  , SHRUBBERY
  , STRUCTURE
  , INFANTRY
  , VEHICLE
  , AIRCRAFT
  , HUGE_VEHICLE
  , DOZER
  , HARVESTER
  , COMMANDCENTER
  , LINEBUILD
  , SALVAGER
  , WEAPON_SALVAGER
  , TRANSPORT
  , BRIDGE
  , LANDMARK_BRIDGE
  , BRIDGE_TOWER
  , PROJECTILE
  , PRELOAD
  , NO_GARRISON
  , WAVEGUIDE
  , WAVE_EFFECT
  , NO_COLLIDE
  , REPAIR_PAD
  , HEAL_PAD
  , STEALTH_GARRISON
  , CASH_GENERATOR
  , DRAWABLE_ONLY
  , MP_COUNT_FOR_VICTORY
  , REBUILD_HOLE
  , SCORE
  , SCORE_CREATE
  , SCORE_DESTROY
  , NO_HEAL_ICON
  , CAN_RAPPEL
  , PARACHUTABLE
  , CAN_BE_REPULSED
  , MOB_NEXUS
  , IGNORED_IN_GUI
  , CRATE
  , CAPTURABLE
  , CLEARED_BY_BUILD
  , SMALL_MISSILE
  , ALWAYS_VISIBLE
  , UNATTACKABLE
  , MINE
  , CLEANUP_HAZARD
  , PORTABLE_STRUCTURE
  , ALWAYS_SELECTABLE
  , ATTACK_NEEDS_LINE_OF_SIGHT
  , WALK_ON_TOP_OF_WALL
  , DEFENSIVE_WALL
  , FS_POWER
  , FS_FACTORY
  , FS_BASE_DEFENSE
  , FS_TECHNOLOGY
  , AIRCRAFT_PATH_AROUND
  , LOW_OVERLAPPABLE
  , FORCEATTACKABLE
  , AUTO_RALLYPOINT
  , TECH_BUILDING
  , POWERED
  , PRODUCED_AT_HELIPAD
  , DRONE
  , CAN_SEE_THROUGH_STRUCTURE
  , BALLISTIC_MISSILE
  , CLICK_THROUGH
  , SUPPLY_SOURCE_ON_PREVIEW
  , PARACHUTE
  , GARRISONABLE_UNTIL_DESTROYED
  , BOAT
  , IMMUNE_TO_CAPTURE
  , HULK
  , SHOW_PORTRAIT_WHEN_CONTROLLED
  , SPAWNS_ARE_THE_WEAPONS
  , CANNOT_BUILD_NEAR_SUPPLIES
  , SUPPLY_SOURCE
  , REVEAL_TO_ALL
  , DISGUISER
  , INERT
  , HERO
  , IGNORES_SELECT_ALL
  , DONT_AUTO_CRUSH_INFANTRY
  , CLIFF_JUMPER
  , FS_SUPPLY_DROPZONE
  , FS_SUPERWEAPON
  , FS_BLACK_MARKET
  , FS_SUPPLY_CENTER
  , FS_STRATEGY_CENTER
  , MONEY_HACKER
  , ARMOR_SALVAGER
  , REVEALS_ENEMY_PATHS
  , BOOBY_TRAP
  , FS_FAKE
  , FS_INTERNET_CENTER
  , BLAST_CRATER
  , PROP
  , OPTIMIZED_TREE
  , FS_ADVANCED_TECH
  , FS_BARRACKS
  , FS_WARFACTORY
  , FS_AIRFIELD
  , AIRCRAFT_CARRIER
  , NO_SELECT
  , REJECT_UNMANNED
  , CANNOT_RETALIATE
  , TECH_BASE_DEFENSE
  , EMP_HARDENED
  , DEMOTRAP
  , CONSERVATIVE_BUILDING
  , IGNORE_DOCKING_BONES
  , ALL
};

enum class CompletionAppearance {
    NONE
  , PLACEMENT
  , RALLY_POINT
};

enum class CommandSource {
    NONE
  , PLAYER
  , SCRIPT
  , AI
};

enum class DamageType {
    EXPLOSION
  , CRUSH
  , ARMOR_PIERCING
  , SMALL_ARMS
  , GATTLING
  , RADIATION
  , FIRE
  , LASER
  , SNIPER
  , POISON
  , HEALING
  , UNRESISTABLE
  , WATER
  , DEPLOY
  , SURRENDER
  , HACK
  , KILLPILOT
  , PENALTY
  , FALLING
  , MELEE
  , DISARM
  , HAZARD_CLEANUP
  , PARTICLE_BEAM
  , TOPPLING
  , INFANTRY_MISSILE
  , AURORA_BOMB
  , LAND_MINE
  , JET_MISSILES
  , STEALTHJET_MISSILES
  , MOLOTOV_COCKTAIL
  , COMANCHE_VULCAN
  , SUBDUAL_MISSILE
  , SUBDUAL_VEHICLE
  , SUBDUAL_BUILDING
  , SUBDUAL_UNRESISTABLE
  , MICROWAVE
  , KILL_GARRISONED
  , STATUS
};

using Damage = float;

enum class DeathType {
    NONE = 0
  , NORMAL
  , CRUSHED
  , BURNED
  , EXPLODED
  , POISONED
  , TOPPLED
  , FLOODED
  , SUICIDED
  , LASERED
  , DETONATED
  , SPLATTED
  , POISONED_BETA
  , EXTRA_2
  , EXTRA_3
  , EXTRA_4
  , EXTRA_5
  , EXTRA_6
  , EXTRA_7
  , EXTRA_8
  , POISONED_GAMMA
  , ALL
};

using Duration = uint32_t;
using Energy = int32_t;

enum class Geometry {
    NONE
  , BOX
  , CYLINDER
  , SPHERE
};

using Health = float;

enum class HealthModifier {
    PRESERVE_RATIO
  , ADD
  , SAME
};

enum class Locomotor {
    NORMAL
  , NORMAL_UPGRADED
  , FREEFALL
  , WANDER
  , PANIC
  , TAXIING
  , SUPERSONIC
  , SLUGGISH
};

enum class ModelCondition {
    TOPPLED
  , FRONTCRUSHED
  , BACKCRUSHED
  , DAMAGED
  , REALLYDAMAGED
  , RUBBLE
  , SPECIAL_DAMAGED
  , NIGHT
  , SNOW
  , PARACHUTING
  , GARRISONED
  , ENEMYNEAR
  , WEAPONSET_VETERAN
  , WEAPONSET_ELITE
  , WEAPONSET_HERO
  , WEAPONSET_CRATEUPGRADE_ONE
  , WEAPONSET_CRATEUPGRADE_TWO
  , WEAPONSET_PLAYER_UPGRADE
  , DOOR_1_OPENING
  , DOOR_1_CLOSING
  , DOOR_1_WAITING_OPEN
  , DOOR_1_WAITING_TO_CLOSE
  , DOOR_2_OPENING
  , DOOR_2_CLOSING
  , DOOR_2_WAITING_OPEN
  , DOOR_2_WAITING_TO_CLOSE
  , DOOR_3_OPENING
  , DOOR_3_CLOSING
  , DOOR_3_WAITING_OPEN
  , DOOR_3_WAITING_TO_CLOSE
  , DOOR_4_OPENING
  , DOOR_4_CLOSING
  , DOOR_4_WAITING_OPEN
  , DOOR_4_WAITING_TO_CLOSE
  , ATTACKING
  , PREATTACK_A
  , FIRING_A
  , BETWEEN_FIRING_SHOTS_A
  , RELOADING_A
  , PREATTACK_B
  , FIRING_B
  , BETWEEN_FIRING_SHOTS_B
  , RELOADING_B
  , PREATTACK_C
  , FIRING_C
  , BETWEEN_FIRING_SHOTS_C
  , RELOADING_C
  , TURRET_ROTATE
  , POST_COLLAPSE
  , MOVING
  , DYING
  , AWAITING_CONSTRUCTION
  , PARTIALLY_CONSTRUCTED
  , ACTIVELY_BEING_CONSTRUCTED
  , PRONE
  , FREEFALL
  , ACTIVELY_CONSTRUCTING
  , CONSTRUCTION_COMPLETE
  , RADAR_EXTENDING
  , RADAR_UPGRADED
  , PANICKING
  , AFLAME
  , SMOLDERING
  , BURNED
  , DOCKING
  , DOCKING_BEGINNING
  , DOCKING_ACTIVE
  , DOCKING_ENDING
  , CARRYING
  , FLOODED
  , LOADED
  , JETAFTERBURNER
  , JETEXHAUST
  , PACKING
  , UNPACKING
  , DEPLOYED
  , OVER_WATER
  , POWER_PLANT_UPGRADED
  , CLIMBING
  , SOLD
  , RAPPELLING
  , ARMED
  , POWER_PLANT_UPGRADING
  , SPECIAL_CHEERING
  , CONTINUOUS_FIRE_SLOW
  , CONTINUOUS_FIRE_MEAN
  , CONTINUOUS_FIRE_FAST
  , RAISING_FLAG
  , CAPTURED
  , EXPLODED_FLAILING
  , EXPLODED_BOUNCING
  , SPLATTED
  , USING_WEAPON_A
  , USING_WEAPON_B
  , USING_WEAPON_C
  , PREORDER
  , CENTER_TO_LEFT
  , LEFT_TO_CENTER
  , CENTER_TO_RIGHT
  , RIGHT_TO_CENTER
  , RIDER1
  , RIDER2
  , RIDER3
  , RIDER4
  , RIDER5
  , RIDER6
  , RIDER7
  , RIDER8
  , STUNNED_FLAILING
  , STUNNED
  , SECOND_LIFE
  , JAMMED
  , ARMORSET_CRATEUPGRADE_ONE
  , ARMORSET_CRATEUPGRADE_TWO
  , USER_1
  , USER_2
  , DISGUISED
};

using Money = uint16_t;
using Percent = uint8_t;

enum class RadarPriority {
    NONE
  , NOT_ON_RADAR
  , STRUCTURE
  , UNIT
  , LOCAL_UNIT
};

enum class Shadow {
    NONE
  , DECAL
  , VOLUME
  , PROJECTION
  , DYN_PROJECTION
  , DIRECTIONAL_PROJECTION
  , ALPHA_DECAL
  , ADDITIVE_DECAL
};

enum class Status {
    NONE = 0
  , DESTROYED
  , CAN_ATTACK
  , UNDER_CONSTRUCTION
  , UNSELECTABLE
  , NO_COLLISIONS
  , NO_ATTACK
  , AIRBORNE_TARGET
  , PARACHUTING
  , REPULSOR
  , HIJACKED
  , AFLAME
  , BURNED
  , WET
  , IS_FIRING_WEAPON
  , BRAKING
  , STEALTHED
  , DETECTED
  , CAN_STEALTH
  , SOLD
  , UNDERGOING_REPAIR
  , RECONSTRUCTING
  , MASKED
  , IS_ATTACKING
  , IS_USING_ABILITY
  , IS_AIMING_WEAPON
  , NO_ATTACK_FROM_AI
  , IGNORING_STEALTH
  , IS_CARBOMB
  , DECK_HEIGHT_OFFSET
  , RIDER1
  , RIDER2
  , RIDER3
  , RIDER4
  , RIDER5
  , RIDER6
  , RIDER7
  , RIDER8
  , FAERIE_FIRE
  , MISSILE_KILLING_SELF
  , REASSIGN_PARKING
  , BOOBY_TRAPPED
  , IMMOBILE
  , DISGUISED
  , DEPLOYED
  , ALL
};

enum class WeaponAffection {
    NONE
  , SELF
  , ENEMY
  , NEUTRAL
  , SUICIDE
  , NOT_SIMILAR
  , NOT_AIRBORNE
};

enum class WeaponBonusCondition {
    INVALID
  , GARRISONED
  , HORDE
  , CONTINUOUS_FIRE_MEAN
  , CONTINUOUS_FIRE_FAST
  , NATIONALISM
  , PLAYER_UPGRADE
  , DRONE_SPOTTING
  , DEMORALIZED
  , ENTHUSIASTIC
  , VETERAN
  , ELITE
  , HERO
  , BATTLEPLAN_BOMBARDMENT
  , BATTLEPLAN_HOLDTHELINE
  , BATTLEPLAN_SEARCHANDDESTROY
  , SUBLIMINAL
  , SOLO_HUMAN_EASY
  , SOLO_HUMAN_NORMAL
  , SOLO_HUMAN_HARD
  , SOLO_AI_EASY
  , SOLO_AI_NORMAL
  , SOLO_AI_HARD
  , TARGET_FAERIE_FIRE
  , FANATICISM
  , FRENZY_ONE
  , FRENZY_TWO
  , FRENZY_THREE
};

enum class WeaponSlot {
    PRIMARY
  , SECONDARY
  , TERTIARY
};

}

#endif
